src/app/editor/layer-settings/settings-container/settings-container.component.ts
Potential fix for : https://github.com/manekinekko/xlayers/issues/2
I'm not sure, that I completely get this task, but, trying to fix it in a more user-friendly way.
**Current state of app**: When user toggles the layer on sketch, or somewhere, he is on the layers-position tab (but, the button doesn't marked as active)
[!https://user-images.githubusercontent.com/1699357/40581355-97467ce0-6156-11e8-9ede-a4867235b118.png]
Also, if you switch tab, for example. to layer-colors, and then, toggle to another layer, you will stay at the layer-colors tab (which, in my opinion is not totally correct, and we have to switch user back to the first tab -> layers-postion)
In this PR I've fixed both issues, with not active css-styles, and also, add the switch to first tab after changing the layer …
=> fix: auto select the layout toggle button when selecting a layer

CONTRIBUTING.md
Fixes #29 
Changed the name of the base branch for PRs from `master` to `develop`.
=> fix(docs): change base branch name from master to develop

src/app/app.module.ts, src/app/core/core.module.ts, src/app/editor/viewer/lib/sketch-dropzone.component.ts, src/app/editor/viewer/lib/sketch-select-demo-files.component.ts, src/app/editor/viewer/lib/sketch.module.ts, src/app/editor/viewer/lib/sketch.service.ts
Implementation for [#21](https://github.com/xlayers/xlayers/issues/21)
Changes:
- now with a select you can choose from different demo Sketch files
=> feat: select for demo Sketch files

src/app/home/landing/landing.component.css, src/app/home/landing/landing.component.html, src/styles.css
The content overflows horizontally on mobile devices due to fixed width of images. This is fixed using a max-width. Also the font-size tends to be too big so it is reduced for small viewports
=> style(home): avoid horizontal scroll on mobile devices

src/app/editor/viewer/lib/sketch.service.ts
We should be able to load the demo files from the current domain/origin and avoid having CORS errors.
=> fix: use current domain as an origin to load demo files

tslint.json
`VS Code`'s auto-linter ran over all folders and my MacAirplane was ready to take off.
=> fix: lint folder exception

src/app/editor/viewer/lib/parsers/sketch-style-parser.service.spec.ts, src/app/editor/viewer/lib/parsers/sketch-style-parser.service.ts, src/app/editor/viewer/lib/sketch-layer.component.ts, src/app/editor/viewer/lib/sketch.service.ts
Many integration difficulties were encountered during the rewriting process of the parser, so I decided to bring all the improvements from the rewrite back to the current parser.
This update includes a version guard at the parser entry, a complete rewrite of each method to separate CSS injection from parsing and fix some bplist parsing error for older version.
=> chore: improved legacy sketch parser

src/app/editor/editor.module.ts
This will disable the `logging` and `redux devtools` when running production.
I think this should be the case  😃
=> perf(core): logging and devtools disabled on prod

.vscode/extensions.json
This will recommend extensions within VSCode. I didn't installed ts lint extension and I never noticed the problem with `"arandomstring"` vs  `'arandomstring'`. 
**Without ts-lint extensions**:
**With
ts-lint extensions**:
This will help our contributers to see this in advance without waiting for the pre-commit checks.
=> core: add workspace recommendations

packages/xlayers/src/app/editor/editor.component.html, packages/xlayers/src/app/editor/editor.component.spec.ts, packages/xlayers/src/app/editor/editor.component.ts
At the moment there is no highlighting
Issue Number: #237 
Zoom In, Out & reset will be highlighted
🎉
=> fix(editor): zooming options will be highlighted

package-lock.json, package.json
lint-staged is not working as expected with the `angular-cli` see: [lint-staged issue](https://github.com/okonet/lint-staged/issues/547)
I think when this issue is resolved we can use it.
For now I implemented pretty-quick as a simple replacement.
Closes #280 
Issue Number: #280
=> build: lint-staged replaced for pretty-quick/prettier

package-lock.json, package.json, packages/sketchapp-parser/src/lib/sketch-style-parser.service.spec.ts, packages/sketchapp-parser/src/lib/sketch-style-parser.service.ts
Fixing type and adding more test on sketch parser.
=> Enrich parser test

packages/xlayers/src/app/editor/preview/viewer/3d-rotation.directive.ts, packages/xlayers/src/app/editor/preview/viewer/sketch-canvas/sketch-canvas.component.ts, packages/xlayers/src/app/editor/preview/viewer/sketch-container/sketch-container.component.ts, packages/xlayers/src/app/editor/preview/viewer/sketch-layer/sketch-layer.component.ts, packages/xlayers/src/app/editor/preview/viewer/sketch-page/sketch-page.component.ts, packages/xlayers/src/app/editor/preview/viewer/viewer.module.ts
=> feat: make the 3d design rotate

src/app/editor/code/editor-container/editor-container.component.css, src/app/editor/code/editor-container/editor-container.component.html
=> feat: new framework selection

src/app/core/sketch.service.ts
- [ X] Bugfix
Pdf parsing is as second last.
Issue Number: #321, #323
Change parsing pdf at first because of changes in sketch file
=> fix(parser): pdf parsing at first

projects/web-codegen/src/lib/angular-aggregator.service.ts, projects/web-codegen/src/lib/angular-element-aggregator.service.ts, projects/web-codegen/src/lib/web-codegen.service.ts, src/app/app.component.ts, src/app/editor/code/editor-container/codegen/angular-element-codegen.service.ts, src/app/editor/code/editor-container/codegen/codegen.module.ts, src/app/editor/code/editor-container/codegen/codegen.service.ts, src/app/editor/code/editor-container/editor-container.component.html, src/app/editor/code/editor-container/editor-container.component.ts, src/assets/codegen/angularElement.svg
Add Angular Element code generation support.
The solution tries to streamline the process described in `ngx-build-plus` by Manfred Steyer (https://github.com/manfredsteyer/ngx-build-plus).
If you generate the assets with the editor and follow the README you will create a minimal toolchain to create Angular Elements in general.
Closes #244
Issue Number: #244
-  [x] add Component codegen
=> feat(codegen): angular element support 244

libs/vue-codegen/src/lib/vue-aggregator.service.ts
A stencil import is written in the vue.js aggregator.
A Vue.js file without stencil import 🙂.
=> Remove stencil import from vue aggregator

.github/workflows/pr_on_development.yml
I think the failing CI has to do with a missing flag in NX, `--with deps` should inspect what dependencies should be build before it will start with one of the other librarys.
I believe this will result in succesfull builds for #373
=> ci: run steps with dependencies

apps/xlayers/src/app/editor/code/exports/stackblitz/stackblitz.angular.service.ts
This PR will resolve a problem in Stackblitz where we refer to a core-js part that is not needed by default
=> fix: remove core-js libs as they are not needed.

apps/xlayers/src/home/interactive-bg/interactive-bg.component.css, apps/xlayers/src/home/interactive-bg/interactive-bg.component.ts, apps/xlayers/src/home/landing/landing.component.css
Improve style of the landing, notably fix an overflow issue on mobile devices.
Overflow on mobile devices and two-three small other spacing issues.
See Screenshots before vs after.
Padding:
Spacing:
Overflow:
Images:
=> style: landing fix mobile devices overflow and improve spacing

apps/xlayers/src/home/interactive-bg/interactive-bg.component.css
In my previous PR #413 I modified the background positioning of `interactive-bg` to improve the spacing. This has for side effect to display the "clickable pink dot" a bit of.
This PR revert the positioning of the background image to align click events and images.
In addition, as discussed in previous PR, it hides the "pulse" button if the screen is not wide enough (I picked 1060px).
Being said, doing so it looses the improvements of the spacing. Maybe something to improve one of these days.
P.S.: Sorry did not noticed these pink dots were clickable and dynamic, would have not modify the property in first place if I would have noticed it...
=> style: landing redo background position

apps/xlayers/src/app/editor/code/exports/stackblitz/stackblitz.angular.service.ts
READMD.md being exported in the wrong directory
Issue Number: #432
READMD.md file is now exported to the root directory of project
Closes #432
=> fix(export): README.md file is exported in the wrong directory in stackblitz
