- src/app/editor/viewer/lib/sketch-canvas.component.ts
Fixes #27 
Changed canvas transform origin to center.
> Editor: change zoom origin to center

- src/app/editor/editor.component.css
- src/app/editor/editor.component.html
- src/app/editor/editor.component.ts
Implementation for sfeir-open-source/xlayers#43.
> feat: resizable sidebar

- src/app/editor/viewer/lib/parsers/sketch-style-parser.service.ts
Implementation for sfeir-open-source/xlayers#46
> fix: overriden style

- src/app/editor/layer-settings/settings-layer-colors/settings-layer-colors.component.ts
- src/app/editor/layer-settings/settings-layer-position/settings-layer-position.component.ts
Implementation for sfeir-open-source/xlayers#37
> chore: read only properties

- package-lock.json
- src/app/editor/layer-settings/layer-settings.module.ts
- src/app/editor/layer-settings/settings-container/settings-container.component.ts
- src/app/editor/layer-settings/settings-preview/settings-layer-colors.component.spec.ts
- src/app/editor/layer-settings/settings-preview/settings-preview.component.ts
- src/app/editor/viewer/lib/sketch-canvas.component.ts
- src/app/editor/viewer/lib/sketch-container.component.ts
Implementation for sfeir-open-source/xlayers#35
> chore: make preview appear in sidebar

- src/app/editor/editor.component.css
- src/app/editor/layer-settings/settings-container/settings-container.component.ts
Implementation for sfeir-open-source/xlayers#34.
> fix: sidebar settings menu

- src/app/core/state/ui.state.ts
- src/app/editor/editor.component.css
- src/app/editor/editor.component.html
- src/app/editor/editor.component.ts
- src/app/editor/layer-settings/settings-container/settings-container.component.ts
- src/app/editor/layer-settings/settings-layer-colors/settings-layer-colors.component.ts
- src/app/editor/layer-settings/settings-preview/settings-preview.component.ts
> fix: rethink the preview process

- src/app/editor/viewer/lib/sketch-canvas.component.spec.ts
- src/app/editor/viewer/lib/sketch-canvas.component.ts
- src/app/editor/viewer/lib/sketch-layer.component.spec.ts
- src/app/editor/viewer/lib/sketch.service.mock.ts
> Fix: unit tests

- firebase.json
- scripts/stamp-build.bash
* chore: merge develop (#9)
* chore: show build number in the editor UI
* docs: add more badges
* docs: update badges
* docs: update readme
* chore: use perl to tag a new build
* chore: updat version pattern
* chore: merge develop (#16)
* docs: update twitter link
* fix: auto select the layout toggle button when selecting a layer (#15)
* chore: merge develop (#17)
* docs: update twitter link
* fix: auto select the layout toggle button when selecting a layer (#15)
* docs: update contributions part
* docs: add CONTRIBUTING guide
* chore: merge develop (#20)
* docs: update twitter link
* fix: auto select the layout toggle button when selecting a layer (#15)
* docs: update contributions part
* docs: add CONTRIBUTING guide
* fix: issue #14
* chore: merge develop (#36)
* docs: add …
> chore: getting master and develop in an even state (#76)

- src/app/editor/viewer/lib/selected-layer.directive.ts
> fix: mouse event compatibility

- src/app/editor/viewer/lib/parsers/sketch-style-parser.service.spec.ts
- src/app/editor/viewer/lib/parsers/sketch-style-parser.service.ts
- src/sketch.typings.ts
Implementation for sfeir-open-source#22.
> Text styling 

- src/app/editor/code-editor/editor-container/codegen/codegen.service.ts
Implementation for https://github.com/xlayers/xlayers/issues/92
> fix: codegen reload

- src/app/editor/editor.component.html
> fix: make button appear after codegen

- src/app/editor/editor.component.html
- src/app/editor/editor.component.ts
- src/app/editor/viewer/lib/sketch-container.component.ts
> chore: close workspace button

- src/app/editor/code-editor/editor-container/codegen/angular/angular.service.ts
- src/app/editor/code-editor/editor-container/codegen/codegen.module.ts
- src/app/editor/code-editor/editor-container/codegen/shared-codegen.service.ts
> refactor: codegen modularization

- src/app/editor/editor.component.html
> fix: remove old stackblitz button

- src/app/editor/editor.component.ts
> fix: close sidebar on closing workspace

- src/app/editor/layer-settings/settings-preview/settings-preview.component.ts
Added a default download icon to the preview. 
Closes: #129
> feature(editor): Download image preview

- package-lock.json
- src/app/editor/code-editor/code-editor.module.ts
- src/app/editor/code-editor/editor-container/editor-container.component.ts
> bug(codeeditor): Fix too many scrollbars

- src/app/editor/viewer/lib/sketch.module.ts
- src/app/editor/viewer/lib/sketch.service.spec.ts
- src/app/editor/viewer/lib/sketch.service.ts
Hi @manekinekko, so I made a change to the `sketchservice`. This change will try to process the sketchfile and if for any reason there is a error in the process we return the parsed data and inform the user. I hope this is the idea you had around this issue, looking forward on your feedback.
Closes: #102
> fix(core): handle unsupported version

- src/app/editor/viewer/lib/sketch-container.component.ts
- src/app/editor/viewer/lib/sketch.service.spec.ts
- src/app/editor/viewer/lib/sketch.service.ts
> fix: unzip crash

- src/app/core/state/page.state.ts
- src/app/core/state/ui.state.ts
- src/app/editor/code-editor/editor-container/codegen/angular/angular.service.ts
- src/app/editor/code-editor/editor-container/codegen/codegen.service.ts
- src/app/editor/code-editor/editor-container/codegen/react/react.service.ts
- src/app/editor/code-editor/editor-container/codegen/vue/vue.service.ts
- src/app/editor/code-editor/editor-container/codegen/wc/wc.service.ts
- src/app/editor/code-editor/editor-container/editor-container.component.spec.ts
- src/app/editor/code-editor/editor-container/editor-container.component.ts
- src/app/editor/editor.component.html
- src/app/editor/editor.component.ts
- src/app/editor/exports/stackblitz/stackblitz.service.ts
> Add independent export button per CodeGen

- src/app/core/core.module.ts
- src/app/editor/editor.module.ts
- src/app/editor/error-report.service.ts
Changed errorhandler to use the store to inform the user.
Closes: #150
> feat(ErrorHandler): New Custom Errorhandler

- angular.json
- package-lock.json
- package.json
- src/app/core/state/ui.state.ts
- src/app/editor/editor.component.ts
- src/app/editor/editor.module.ts
- src/app/editor/tree-view/tree-view.component.ts
- src/app/editor/viewer/lib/sketch-canvas.component.ts
- src/app/editor/viewer/lib/sketch.service.ts
> feat: add support for pdf previews

- packages/sketchapp-parser/src/lib/sketch-style-parser.service.ts
- packages/xlayers/src/app/core/state/ui.state.ts
> Fix: Autofix page position

- package-lock.json
- package.json
- packages/xlayers/src/app/editor/error-report.service.ts
> refactor(app): Remove bugsnag client

- packages/xlayers/src/app/core/state/ui.state.ts
- packages/xlayers/src/app/editor/editor.component.html
- packages/xlayers/src/app/editor/editor.component.ts
> Add zoom reset icon

- angular.json
- package-lock.json
- package.json
- packages/xlayers/src/app/editor/viewer/lib/sketch.service.ts
I also removed `pdf-js` as I believe can ignore this dependency for now.
Closes #200
> fix(editor): Removed PDF preview for now

- packages/xlayers/src/app/editor/viewer/lib/sketch-canvas.component.ts
> Fix: Independent drag

- .commitlintrc.json
- package-lock.json
- package.json
Because I'm always making errors in the `commit message` I added this commitlint that verify's is the basics from the [commit message format](https://github.com/xlayers/xlayers/blob/master/CONTRIBUTING.md#commit)
> chore: verify commit message before commiting

- packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.ts
> fix: preview border

- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/angular/angular.service.spec.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/codegen.service.spec.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/lit-element/lit-element.service.spec.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/react/react.service.spec.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/shared-codegen.service.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/stencil/stencil.service.spec.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/vue/vue.service.spec.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/wc/wc.service.spec.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-container.component.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.spec.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-page.component.spec.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-page.component.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch.service.spec.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch.service.ts
- tests/integration/sketch-parsing.spec.ts
> feat: add images assets support

- .vscode/launch.json
- jest.config.js
- package.json
- packages/sketchapp-parser/src/lib/sketch-style-parser.service.spec.ts
- packages/sketchapp-parser/src/lib/sketch-style-parser.service.ts
- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/shared-codegen.service.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-layer.component.ts
- packages/xlayers/src/app/editor/viewer/lib/sketch-page.component.ts
Fixes: #90
Some separate solids will be made separately using the doc in the wiki.
> Add SVG basic solid

- packages/xlayers/src/app/editor/editor.component.css
- packages/xlayers/src/app/editor/editor.component.html
> refactor: update app title for more consistency

- package-lock.json
- package.json
> chore: add lint-staged

- packages/xlayers/src/app/editor/preview-badge.service.spec.ts
> test: implemented for the badge service

- packages/xlayers/src/app/editor/code-editor/editor-container/codegen/codegen.service.spec.ts
- packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.angular.service.spec.ts
- packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.lit-element.service.spec.ts
- packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.react.service.spec.ts
> test: add some extra test around stackblitz services

- packages/xlayers/src/app/core/state/ui.state.ts
Spread operator is used for nested state operations.
Refactored to use [NGXS Patch Operators](https://ngxs.gitbook.io/ngxs/advanced/operators), available as of ngxs@4.3.0. These serve the same function, but allow to clean up said immutable operations a bit, producing the same result.
Not all use cases of `patchState` need to be refactored to use patch operators—at least not for the time being. The result is the same for shallow operations given that they're [using the patch operators internally now as well](https://github.com/ngxs/store/blob/v3.4.1/packages/store/src/internal/state-context-factory.ts#L58).
> refactor(core): ngxs patch operators to simplify nested state operations

- package.json
- packages/xlayers/src/app/app.module.ts
- packages/xlayers/src/app/editor/editor.component.css
- packages/xlayers/src/app/editor/editor.component.html
> refactor: enable BrowserAnimationsModule

- packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.stencil.service.spec.ts
- packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.vue.service.spec.ts
- packages/xlayers/src/app/editor/exports/stackblitz/stackblitz.wc.service.spec.ts
> test: all framework services are tested

- packages/xlayers/src/app/editor/code/editor-container/editor-container.component.css
- packages/xlayers/src/app/editor/editor.component.html
- packages/xlayers/src/app/editor/editor.component.ts
- packages/xlayers/src/app/editor/preview/preview.component.ts
- packages/xlayers/src/app/upload/upload.component.ts
> fix: small fixes after restructure

- packages/xlayers/src/index.html
> fix: twitter card

- packages/sketchapp-parser/src/lib/sketch-style-parser.service.ts
Fixes: #279 
Using SVG attribute instead of style.
> fix: svg invalid inline style

- packages/sketchapp-parser/src/lib/sketch-style-parser.service.ts
SVG show [object] instead of the element.
Fixing it.
> fix: remove svg from shape property

- src/app/upload/dropzone/dropzone.component.css
- src/app/upload/upload.component.css
- src/app/upload/upload.component.html
- src/app/upload/upload.component.ts
Closes 270
Small style changes
A border will be highlighted on dragging, second I removed the white background color.
> feat(app): hightlight dropzone when dragging over it

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
> feat: add edge debug

- .github/ISSUE_TEMPLATE/ui-designer-tool--add-support-for---ui-tool--.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> docs: fixed some parts in readme and github template

- package-lock.json
> chore: update dependencies lock

- src/app/editor/code/editor-container/editor-container.component.ts
code editor reference issue
Closes #318
Issue Number: #318
> fix(editor): fixes code editor undefined reference issue

- src/app/editor/code/editor-container/codegen/angular-codegen.service.ts
At this moment you have the wrong reference when extracting locally.
Issue Number: #333 
When downloading you can use it as is.
> fix: remove ts from end of file 

- package-lock.json
- src/app/upload/select-demo-files/select-demo-files.component.css
- src/app/upload/select-demo-files/select-demo-files.component.html
- src/app/upload/upload.component.css
- src/home/landing/landing.component.css
Currently the home page is not mobile friendly . 
Issue Number: #315 
It is responsive now.
> feat(ui): make home page responsive

- .github/workflows/pr_on_development.yml
- .github/workflows/push_on_master.yml
- CONTRIBUTING.md
- README.md
- apps/xlayers/src/app/core/preview-badge.service.ts
- apps/xlayers/src/app/editor/preview-badge.service.spec.ts
- apps/xlayers/src/assets/i18n/en.json
- apps/xlayers/src/assets/i18n/nl.json
- nx.json
> chore: rename "master" to "main"

- apps/xlayers-e2e/src/specs/interactions.spec.ts
See https://github.com/electron/electron/issues/20944 for more details
> chore: ignore 3d toggle e2e test in Electron

- .github/workflows/pr_on_development.yml
- .github/workflows/push_to_main.yml
Hi @manekinekko, I've finally fixed the branching problems we faced. One of the Nrwl Members helped us, we now pull the main branch and for all the affected code it will run the lint ,test,e2e and build. Build is depended on test and e2e.
Ohw, and it shares the node_modules on the different OS and different versions.
> ci: handle branching correctly in PR workflow

- .github/workflows/pr_on_development.yml
> ci: add env files for nx plugin

- angular.json
> chore: allowed commonJs dependencies

- angular.json
- apps/xlayers/src/app/core/state/ui.state.ts
- apps/xlayers/src/app/upload/upload.component.ts
- apps/xlayers/src/main.ts
- apps/xlayers/tsconfig.app.json
- package-lock.json
- package.json
> Fix error handling

- .github/workflows/pr_on_development.yml
- .github/workflows/push_to_main.yml
> ci: reduce CI workflows

- package-lock.json
- package.json
> fix: update package with severe CVE

- .release-it.json
- CHANGELOG.md
- package-lock.json
- package.json
With this change, we generate a `CHANGELOG` everytime we deploy.
> chore: add script for generating changelog

- .github/workflows/pr_on_development.yml
We were having issues with the cached `node_modules`, for now I've resolved this by installing everything for the E2E step.
- [ X] No
> Run E2E correctly on a PR

- .github/workflows/pr_on_development.yml
- .github/workflows/push_to_main.yml
> ci: handle node version correct

- libs/css-codegen/src/lib/css-parser.service.ts
- libs/sketchtypes/src/lib/sketchtypes.ts
> fix: ignore undefined style info

- apps/xlayers-e2e/src/integration/app.spec.ts
- apps/xlayers/src/app/editor/code/code.component.spec.ts
- apps/xlayers/src/app/editor/code/editor-container/editor-container.component.spec.ts
- apps/xlayers/src/app/editor/preview/layer-settings/settings-container/settings-container.component.spec.ts
- apps/xlayers/src/app/editor/preview/layer-settings/settings-layer-colors/settings-layer-colors.component.spec.ts
- apps/xlayers/src/app/editor/preview/layer-settings/settings-layer-position/settings-layer-position.component.spec.ts
- apps/xlayers/src/app/editor/preview/layer-settings/settings-layer-properties/settings-layer-properties.component.spec.ts
- apps/xlayers/src/app/editor/preview/layer-settings/settings-preview/settings-layer-colors.component.spec.ts
- apps/xlayers/src/app/editor/preview/layer-tree-layout/layer-tree-layout.component.spec.ts
- apps/xlayers/src/app/editor/preview/preview.component.spec.ts
- apps/xlayers/src/app/editor/preview/viewer/canvas/canvas.component.spec.ts
- apps/xlayers/src/app/editor/preview/viewer/container/container.component.spec.ts
- apps/xlayers/src/app/editor/preview/viewer/layer/layer.component.spec.ts
- apps/xlayers/src/app/editor/preview/viewer/page/page.component.spec.ts
- apps/xlayers/src/app/upload/browse-files/browse-files.component.spec.ts
- apps/xlayers/src/app/upload/dropzone/dropzone.component.spec.ts
- apps/xlayers/src/app/upload/select-demo-files/select-demo-files.component.spec.ts
- apps/xlayers/src/app/upload/upload.component.spec.ts
- apps/xlayers/src/home/interactive-bg/interactive-bg.component.spec.ts
- apps/xlayers/src/home/landing/landing.component.spec.ts
- jest.preset.js
- libs/angular-codegen/src/lib/angular-aggregator.service.ts
- libs/css-codegen/src/lib/css-codegen.service.spec.ts
> refactor: change deprecated api async to waitForAsync

- apps/xlayers/src/app/editor/code/exports/stackblitz/stackblitz.service.ts
- apps/xlayers/src/app/editor/editor.component.ts
Issue Number: #427 
Closes #427
> fix: stackblitz export not working

- apps/xlayers/src/app/upload/upload.component.ts
Closes #429
Issue Number: #429
> fix(test): e2e test is failing in main branch
